# Publish all joint states -----------------------------------
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# Position Controllers ---------------------------------------
joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_joint
    pid: {p: 0.4, i: 0.01, d: 0.01}
