<?xml version="1.0"?>
<!--
MIT License

Copyright (c) 2022 Gotelli Andrea

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->


<!-- Revolute-Revolute Manipulator -->
<robot name="robot_limb" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants for joint dimensions -->
    <xacro:property name="mass" value="0.1" />
    <xacro:property name="width" value="0.05" />
    <xacro:property name="height" value="0.1" />

    <!-- Position of the base joint -->
    <xacro:arg name="x" default="0.0"/>
    <xacro:arg name="y" default="0.0"/>
    <xacro:arg name="roll" default="0.0"/>
    <xacro:arg name="pitch" default="0.0"/>
    <xacro:arg name="yaw" default="0.0"/>

    <!-- Orientation of the attach point -->
    <xacro:arg name="a_roll" default="0.0"/>
    <xacro:arg name="a_pitch" default="0.0"/>
    <xacro:arg name="a_yaw" default="0.0"/>


    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>



    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>

    <!-- Base Link -->
    <link name="base_joint_body">
        <collision name="base_joint_body_collision">
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <geometry>
                <!--<box size="${width} ${width} ${height}"/>-->
                <cylinder length="${height}" radius="${width/2}"/>
            </geometry>
        </collision>

        <visual name="base_joint_body_visual">
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <geometry>
                <!--<box size="${width} ${width} ${height}"/>-->
                <cylinder length="${height}" radius="${width/2}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <inertial>
        <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
        ixx="${mass / 12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height*height + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
    </link>

    <!-- Link1 Properties-->
    <gazebo reference="base_joint_body">
        <material>Gazebo/Orange</material>
    </gazebo>

    <material name="orange">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
    </material>


    <joint name="base_joint" type="continuous">
        <parent link="world"/>
        <child link="base_joint_body"/>
        <origin xyz="$(arg x) $(arg y) 0" rpy="$(arg roll) $(arg pitch) $(arg yaw)"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="attach_point">
        <!--<collision name="attach_point_collision">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${width/10} ${width/10} ${width/10}"/>
            </geometry>
        </collision>-->

        <visual name="attach_point_visual">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${width/10} ${width/10} ${width/10}"/>
            </geometry>
        </visual>

        <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass/10}"/>
        <inertia
        ixx="${mass / 12.0 * 2*(width*width/100)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * 2*(width*width/100)}" iyz="0.0"
        izz="${mass / 12.0 * 2*(width*width/100)}"/>
        </inertial>
    </link>

    <gazebo reference="attach_point">
        <material>Gazebo/Black</material>
    </gazebo>


    <joint name="fix_rod_to_joint" type="fixed">
        <parent link="base_joint_body"/>
        <child link="attach_point"/>
        <origin xyz="0 ${width/2} 0" rpy="$(arg a_roll) $(arg a_pitch) $(arg a_yaw)"/>
    </joint>

    <!-- Tell gazebo not to lump fixed joint togheter-->
    <gazebo reference="fix_rod_to_joint">
        <preserveFixedJoint>true</preserveFixedJoint>
    </gazebo>


    <transmission name="base_joint_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="base_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


</robot>
