<?xml version="1.0"?>
<!--
MIT License

Copyright (c) 2022 Gotelli Andrea

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->


<!-- Revolute-Revolute Manipulator -->
<robot name="robot_limb" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <!-- Position of the base joint -->
    <xacro:arg name="x" default="0.0"/>
    <xacro:arg name="y" default="0.0"/>
    <xacro:arg name="z" default="0.0"/>
    <xacro:arg name="roll" default="0.0"/>
    <xacro:arg name="pitch" default="0.0"/>
    <xacro:arg name="yaw" default="0.0"/>

    <xacro:arg name="widthx" default="0.05"/>
    <xacro:arg name="widthy" default="0.05"/>
    <xacro:arg name="height" default="0.1"/>

    <xacro:arg name="mass" default="0.1"/>

    <xacro:arg name="axis" default="0 0 1"/>

    <xacro:arg name="a_x" default="0.0"/>
    <xacro:arg name="a_y" default="0.0"/>
    <xacro:arg name="a_z" default="$(arg height)"/>
    <xacro:arg name="a_roll" default="0.0"/>
    <xacro:arg name="a_pitch" default="0.0"/>
    <xacro:arg name="a_yaw" default="0.0"/>


    <!-- Constants for joint dimensions -->
    <xacro:property name="mass" value="$(arg mass)" />
    <xacro:property name="axis" value="$(arg axis)" />
    <xacro:property name="widthx" value="$(arg widthx)" />
    <xacro:property name="widthy" value="$(arg widthy)" />
    <xacro:property name="height" value="$(arg height)" />

    <xacro:property name="ap_relative_pose" value="$(arg a_x) $(arg a_y) $(arg a_z)" />
    <xacro:property name="ap_relative_orientation" value="$(arg a_roll) $(arg a_pitch) $(arg a_yaw)" />



    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>



    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>

    <!-- Base Link -->
    <link name="base_joint_body">
        <collision name="base_joint_body_collision">
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${widthx} ${widthy} ${height}"/>
            </geometry>
            <!--<geometry>
                <cylinder radius="${width}" length="${height1}"/>
            </geometry>-->
            <contact_coefficients mu="0.0" kp="0.0" kd="0.0"/>
        </collision>

        <visual name="base_joint_body_visual">
            <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${widthx} ${widthy} ${height}"/>
            </geometry>
            <!--<geometry>
                <cylinder radius="${width}" length="${height1}"/>
            </geometry>-->
            <material name="orange"/>
        </visual>

        <inertial>
        <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
        ixx="${mass / 12.0 * (widthy*widthy + height*height)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height*height + widthx*widthx)}" iyz="0.0"
        izz="${mass / 12.0 * (widthx*widthx + widthy*widthy)}"/>
        </inertial>
    </link>

    <!-- Link1 Properties-->
    <gazebo reference="base_joint_body">
        <material>Gazebo/Orange</material>
    </gazebo>

    <material name="orange">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
    </material>


    <joint name="base_joint" type="prismatic">
        <parent link="world"/>
        <child link="base_joint_body"/>  
        <limit effort="1000.0" lower="-1" upper="0.4" velocity="0.5"/>
        <!--<axis xyz="1 0 0"/>-->
        <axis xyz="${axis}"/>
        <origin xyz="$(arg x) $(arg y) $(arg z)" rpy="0 0 $(arg yaw)"/>
    </joint>


    <link name="attach_point">
        <collision name="attach_point_collision">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.005 0.005 0.005"/>
            </geometry>
        </collision>

        <visual name="attach_point_visual">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.005 0.005 0.005"/>
            </geometry>
        </visual>

        <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass/10}"/>
        <inertia
        ixx="${mass / 12.0 * 2*(0.005**2)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * 2*(0.005**2)}" iyz="0.0"
        izz="${mass / 12.0 * 2*(0.005**2)}"/>
        </inertial>
    </link>

    <gazebo reference="attach_point">
        <material>Gazebo/Black</material>
    </gazebo>


    <joint name="fix_rod_to_joint" type="fixed">
        <parent link="base_joint_body"/>
        <child link="attach_point"/>
        <origin xyz="${ap_relative_pose}" rpy="${ap_relative_orientation}"/>
    </joint>

<!-- Tell gazebo not to lump fixed joint togheter-->
    <gazebo reference="fix_rod_to_joint">
        <preserveFixedJoint>true</preserveFixedJoint>
    </gazebo>


    <transmission name="base_joint_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="base_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="base_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


</robot>
